name: Print_info
on: [push, workflow_dispatch]
jobs:
  cond:
     runs-on: ubuntu-latest
     steps:
      - name: Conditional
        if: ${{github.event_name == 'push' }} # 깃허브에 푸시할 때만 실행
        run: echo "This runs on push events only."
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ github.repository }}" # 깃허브 저장소 이름 출력